SS/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", views.main, name="main"),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("articles/", include("articles.urls")),
    path("gathering/", include("gathering.urls")),
    path("free/", include("free.urls")),
    path("notices/", include("notices.urls")),
    path("search/", views.search, name="search"),
    path("calendars/", include("calendars.urls")),
    path("mdeditor/", include("mdeditor.urls")),
    path("notes/", include("notes.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

free/urls.py
from django.urls import path
from . import views

app_name = "free"

urlpatterns = [
    # 자유게시글
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:free_pk>/", views.detail, name="detail"),
    path("<int:free_pk>/update/", views.update, name="update"),
    path("<int:free_pk>/delete/", views.delete, name="delete"),
    path("fail/", views.fail, name="fail"),
    # 댓글
    path("<int:free_pk>/comments_create/", views.comment_create, name="comment_create"),
    path("<int:free_pk>/comment_delete/<int:comment_pk>/delete/",views.comment_delete,name="comment_delete"),
    path("<int:free_pk>/comment_update/<int:comment_pk>/update/",views.comment_update,name="comment_update"),
    path("<int:free_pk>/recomment_create/<int:comment_pk>/", views.recomment_create, name='recomment_create'),
    path("<int:free_pk>/recomment_delete/<int:comment_pk>/delete/<int:recomment_pk>/", views.recomment_delete, name="recomment_delete"),
    path("<int:free_pk>/like/", views.like, name="like"),
    path("search/", views.search, name="search"),
]

free/models.py
from django.db import models
from django.conf import settings
from mdeditor.fields import MDTextField

# Create your models here.


class Free(models.Model):
    check = models.BooleanField(default=False)
    title = models.CharField(max_length=50)
    create_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    content = MDTextField()
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    like_free = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_free"
    )
    hits = models.PositiveIntegerField(default=0, verbose_name="조회수")
    q = models.CharField(max_length=5, default="자유")


class Photo(models.Model):
    free = models.ForeignKey(Free, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="images/", blank=True)


class Comment(models.Model):
    content = models.TextField()
    free = models.ForeignKey(Free, on_delete=models.CASCADE, related_name="free_user")
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="free_com_user"
    )
    unname = models.BooleanField(default=True)


class ReComment1(models.Model):
    comment = models.ForeignKey(
        Comment, on_delete=models.CASCADE, related_name="free_comment_user"
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    body = models.CharField("답글", max_length=200)
    updated_at = models.DateTimeField(auto_now=True)
    unname = models.BooleanField(default=True)

free/forms.py
from django import forms
from .models import Free, Comment, ReComment1, Photo
from django.forms import ClearableFileInput


class FreeForm(forms.ModelForm):
    class Meta:
        model = Free
        fields = [
            "title",
            "content",
        ]

        widgets = {
            "title": forms.TextInput(
                attrs={
                    "placeholder": "제목을 입력해주세요.",
                }
            ),
        }

        labels = {
            "title": "",
            "content": "",
        }


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = [
            "image",
        ]
        widgets = {
            "image": ClearableFileInput(
                attrs={
                    "multiple": True,
                    "onchange": "setThumbnail(event)",
                }
            ),
        }
        labels = {
            "image": "이미지를 선택해주세요.",
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            "content",
        ]

        widgets = {
            "content": forms.Textarea(
                attrs={
                    "class": "form-control",
                    "rows": 1,
                }
            ),
        }

        labels = {
            "content":"",
        }
class ReCommentForm(forms.ModelForm):
    class Meta:
        model = ReComment1
        fields = [
            "body",
        ]
        widgets = {
            "body": forms.Textarea(attrs={"class": "form-control", "rows": 1}),
        }

free/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from .forms import FreeForm, CommentForm, ReCommentForm, PhotoForm
from accounts.models import User, Notification
from django.db.models import Count
from django.db.models import Q
from datetime import date, datetime, timedelta
import json
from django.core.paginator import Paginator

# Create your views here.
def maketable(p):
    table = [0] * len(p)
    i = 0
    for j in range(1, len(p)):
        while i > 0 and p[i] != p[j]:
            i = table[i - 1]
        if p[i] == p[j]:
            i += 1
            table[j] = i
    return table


def KMP(p, t):
    ans = []
    table = maketable(p)
    i = 0
    for j in range(len(t)):
        while i > 0 and p[i] != t[j]:
            i = table[i - 1]
        if p[i] == t[j]:
            if i == len(p) - 1:
                ans.append(j - len(p) + 2)
                i = table[i]
            else:
                i += 1
    return ans


def index(request):
    frees = Free.objects.order_by("-pk")  # 최신순으로나타내기

    page = request.GET.get("page", "1")
    paginator = Paginator(frees, 10)
    page_obj = paginator.get_page(page)
    if request.user.is_authenticated:
        user = User.objects.get(pk=request.user.pk)
        new_message = Notification.objects.filter(Q(user=user.pk) & Q(check=False))
        message_count = len(new_message)
    else:
        message_count = 0
    context = {
        "count": message_count,
        "frees": frees,
        "question_list": page_obj,
    }
    return render(request, "free/index.html", context)


@login_required
def create(request):
    if request.method == "POST":
        form = FreeForm(request.POST, request.FILES)
        photo_form = PhotoForm(request.POST, request.FILES)
        images = request.FILES.getlist("image")
        if form.is_valid() and photo_form.is_valid():
            free = form.save(commit=False)
            free.user = request.user
            if len(images):
                for image in images:
                    image_instance = Photo(free=free, image=image)
                    free.save()
                    image_instance.save()
            else:
                free.save()
            return redirect("free:index")
    else:
        form = FreeForm()
        photo_form = PhotoForm()
    if request.user.is_authenticated:
        user = User.objects.get(pk=request.user.pk)
        new_message = Notification.objects.filter(Q(user=user.pk) & Q(check=False))
        message_count = len(new_message)
    context = {
        "count": message_count,
        "form": form,
        "photo_form": photo_form,
    }
    return render(request, "free/create.html", context)


@login_required
def detail(request, free_pk):
    free = Free.objects.get(pk=free_pk)
    comments = Comment.objects.filter(free_id=free_pk).order_by("-pk")

    comment_form = CommentForm()
    recomment_form = ReCommentForm()

    comment_form.fields["content"].widget.attrs["placeholder"]="댓글을 남겨주세요!\n댓글이 길어질 땐 댓글창을 늘려보세요."
    recomment_form.fields["body"].widget.attrs["placeholder"]="답글을 남겨보세요!\n답글이 길어질 땐 답글창을 늘려보세요."

    
    photos = free.photo_set.all()
    for i in comments:  # 시간바꾸는로직
        i.updated_at = i.updated_at.strftime("%Y.%m.%d. %H:%M %p")
        with open("filtering.txt", "r", encoding="utf-8") as txtfile:
            for word in txtfile.readlines():
                word = word.strip()
                ans = KMP(word, i.content)
                if ans:
                    for k in ans:
                        k = int(k)
                        if k < len(i.content) // 2:
                            i.content = (
                                len(i.content[k - 1 : len(word)]) * "*"
                                + i.content[len(word) :]
                            )
                        else:
                            i.content = (
                                i.content[0 : k - 1] + len(i.content[k - 1 :]) * "*"
                            )
    if request.user.is_authenticated:
        user = User.objects.get(pk=request.user.pk)
        new_message = Notification.objects.filter(Q(user=user.pk) & Q(check=False))
        message_count = len(new_message)
    context = {
        "count": message_count,
        "free": free,
        "comment_form": comment_form,
        "recomment_form": recomment_form,
        "comments": comments,
        "photos": photos,
    }

    response = render(request, "free/detail.html", context)

    expire_date, now = datetime.now(), datetime.now()
    expire_date += timedelta(days=1)
    expire_date = expire_date.replace(hour=0, minute=0, second=0, microsecond=0)
    expire_date -= now
    max_age = expire_date.total_seconds()

    cookievalue = request.COOKIES.get("hitfree", "")

    if f"{free_pk}" not in cookievalue:
        cookievalue += f"{free_pk}"
        response.set_cookie(
            "hitfree", value=cookievalue, max_age=max_age, httponly=True
        )
        free.hits += 1
        free.save()
    return response


@login_required
def update(request, free_pk):
    free = Free.objects.get(pk=free_pk)
    user = User.objects.get(pk=request.user.pk)
    if request.user == free.user:
        photos = free.photo_set.all()
        instancetitle = free.title
        if request.method == "POST":
            free_form = FreeForm(request.POST, request.FILES, instance=free)
            if photos:
                photo_form = PhotoForm(request.POST, request.FILES, instance=photos[0])
            else:
                photo_form = PhotoForm(request.POST, request.FILES)
            images = request.FILES.getlist("image")
            for photo in photos:
                if photo.image:
                    photo.delete()
            if free_form.is_valid() and photo_form.is_valid():
                free = free_form.save(commit=False)
                free.check = True
                free.user = request.user
                if len(images):
                    for image in images:
                        image_instance = Photo(free=free, image=image)
                        free.save()
                        image_instance.save()
                else:
                    free.save()
                return redirect("free:detail", free.pk)
        else:
            free_form = FreeForm(instance=free)
            if photos:
                photo_form = PhotoForm(instance=photos[0])
            else:
                photo_form = PhotoForm()
        if request.user.is_authenticated:
            new_message = Notification.objects.filter(
                Q(user_id=user.pk) & Q(check=False)
            )
            message_count = len(new_message)
            print(message_count)
            context = {
                "count": message_count,
                "free_form": free_form,
                "photo_form": photo_form,
                "instancetitle": instancetitle,
                "free": free,
            }
        else:
            context = {
                "free_form": free_form,
                "photo_form": photo_form,
                "instancetitle": instancetitle,
                "free": free,
            }
        return render(request, "free/update.html", context)
    else:
        return redirect("free:index")


@login_required
def delete(request, free_pk):
    free = Free.objects.get(pk=free_pk)
    free.delete()
    return redirect("free:index")


def fail(request):
    if request.user.is_authenticated:
        user = User.objects.get(pk=request.user.pk)
        new_message = Notification.objects.filter(Q(user=user.pk) & Q(check=False))
        message_count = len(new_message)
    context = {
        "count": message_count,
    }
    return render(request, "free/fail.html", context)


@login_required
def comment_create(request, free_pk):
    free = Free.objects.get(pk=free_pk)
    comment_form = CommentForm(request.POST)
    recomment_form = ReCommentForm(request.POST)
    user = request.user.pk
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.free = free
        comment.user = request.user
        comment.save()
        if comment.unname:
            message = f"자유게시판 {free.title}의 글에 {'익명' + str(user)}님이 댓글을 달았습니다."
        else:
            message = f"자유게시판 {free.title}의 글에 {user}님이 댓글을 달았습니다."
        Notification.objects.create(
            user=free.user, message=message, category="자유", nid=free.pk
        )
    temp1 = Comment.objects.filter(free_id=free_pk).order_by("-pk")
    comment_data = []
    recomment_data2 = []
    for t in temp1:
        temp2 = ReComment1.objects.filter(comment_id=t.pk).order_by("-pk")
        t.updated_at = datetime.now().strftime("%Y. %m. %d. %H:%M")
        with open("filtering.txt", "r", encoding="utf-8") as txtfile:
            for word in txtfile.readlines():
                word = word.strip()
                ans = KMP(word, t.content)
                if ans:
                    for k in ans:
                        k = int(k)
                        if k < len(t.content) // 2:
                            t.content = (
                                len(t.content[k - 1 : len(word)]) * "*"
                                + t.content[len(word) :]
                            )
                        else:
                            t.content = (
                                t.content[0 : k - 1] + len(t.content[k - 1 :]) * "*"
                            )
        if t.unname:
            t.user.username = "익명" + str(t.user_id)
        comment_data.append(
            {
                "id": t.user_id,
                "userName": t.user.username,
                "content": t.content,
                "commentPk": t.pk,
                "updated_at": t.updated_at,
                "recomment_cnt": temp2.count(),
                "unname": t.unname,
            }
        )
        for r in temp2:

free/templates/free/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'free/css/create.css' %}">
{% endblock css %}

{% block content %}
<div class="create-container">
  <p class="title">
    <a href="{% url 'free:index' %}">COMMUNITY BOARD</a><br><span class="state-change">CREATE</span>
  </p>
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <div class="container text-center">
      <div class="row">
    <div class="buttons">
        <div class="col-xl-2 col-lg-3 col-md-4 col-sm-6">
          <button type="submit" class="btn submit-button" id="submit_btn">작성</button>
        </div>
        <div class="col-xl-2 col-lg-3 col-md-4 col-sm-6">
        <button id="cancel_btn"><a href="{% url 'free:index' %}" class="btn cancel_btn" >취소</a></button>
        </div>
      </div>  
      </div>
    </div>
  </form>
</div> <!-- create-container -->
{% endblock content %}

{% block js %}
{% endblock js %}

free/templates/free/detail.html
{% extends 'base.html' %}

{% load django_bootstrap5 %}
{% load static %}

{% block css %}
  <link rel="stylesheet" href="{% static 'free/css/detail.css' %}">
{% endblock css %}

{% block content %}
  <div class="detail-container">
    <!-- 자유게시판 -->
    <p class="title">COMMUNITY BOARD</p>
    <!-- 글 제목 -->
    <p class="free-title">{{free.title}}</p>

    <!-- 제목 아래 정보 -->
    <div class="sub-title">
      <div class="user-date">
        <!-- 작성자 -->
        <p class="user">익명{{free.user.pk}}</p>

        <!-- 작성일자 -->
        {% if not free.check %}
          <p class="date">{{free.create_at|date:'Y.m.d H:i A'}}</p>
          <!-- 글이 수정될 경우 (수정됨)이 붙음 -->
        {% else %}
          <p class="edited">{{free.updated_at|date:'Y.m.d H:i A'}}
            (수정됨)</p>
        {% endif %}
        {% if request.user == free.user %}
          <div class="buttons">
            <!-- 수정 버튼 -->
            <a href="{% url 'free:update' free.pk %}" class="edit-button">수정</a>

            <!-- 삭제 버튼 -->
            <form action="{% url 'free:delete' free.pk %}" method="POST">
              {% csrf_token %}
              <input type="submit" value="삭제" class="delete-button">
            </form>
          </div>
          <!-- buttons -->
        {% endif %}
        <!-- % if request.user == free.user % -->
      </div>
      <!-- user-date -->

      <!-- 기타 정보 -->
      <p class="views">
        <!--<img src="https://cdn-icons-png.flaticon.com/512/159/159604.png" class="views-icon" alt="조회수 아이콘">-->
        조회수
        {{ free.hits }}
        ㅣ 좋아요
        {{ free.like_free.count }}
        ㅣ 댓글 수
        {{ free.free_user.count }}
      </p>
      <!-- views -->
    </div>
    <!-- sub-title -->

    <!-- 글 내용 -->
    <p class="free-contents" id="content">
      <textarea>{{ free.content }}</textarea>
    </p>

    {% if photos %}
      {% for photo in photos %}
        <img src="{{ photo.image.url }}" class="free-img">
      {% endfor %}
    {% endif %}

    <!-- 여기 태그 안 넣나요? <p>#잡담 #어쩌구 #안_넣으면_지워서_넘겨주세요 #하게되면길게는못하게막아야겠지</p>-->

    <!-- 좋아요 -->
    {% if request.user.is_authenticated %}
      <div class="heart">
        {% if request.user not in free.like_free.all %}
          <i data-like-id="{{ free.pk }}" id="like-btn" class="bi bi-heart free-heart"></i>
        {% else %}
          <i data-like-id="{{ free.pk }}" id="like-btn" class="bi bi-heart-fill free-heart-fill"></i>
        {% endif %}
        <p id="likes">{{ free.like_free.count }}</p>
      </div>
    {% endif %}

    <!-- 댓글 작성 폼 -->
    {% if request.user.is_authenticated %}
      <form id="comment-form" data-free-id="{{ free.pk }}" action="{% url 'free:comment_create' free.pk %}" method="POST">
        {% csrf_token %}
        {% bootstrap_form comment_form %}
        <div class="sb-div"><input class="submit-button" type="submit" value="작성"></div>
      </form>
    {% endif %}
    <!-- % if request.user.is_authenticated % -->

    <!-- 작성된 댓글 수 -->
    <p id="comment_count">댓글
      {{ comments.count }}개</p>
    <hr class="comment-start">

    <!-- 작성된 댓글 전체 -->
    <div id="comments">
      {% for comment in comments %}
        <!-- 댓글 작성자라면 수정/삭제 버튼이 보임 -->
        {% if request.user.pk == comment.user.pk %}
          <div class="comment-title">
            <div class="user-date">
              <!-- 작성자 -->
              <p class="comment-user">익명{{ comment.user.pk}}</p>
              <!-- 작성일자 -->
              <p class="date">{{comment.updated_at}}</p>
            </div>

            <div class="comment-buttons">
              <!-- 수정 버튼 -->
              <button onclick="update_comment(this)" id="comment-update-{{ comment.pk }}" data-freeup-id="{{ free.pk }}" data-commentup-id="{{ comment.pk }}" class="edit-button">수정</button>

              <!-- 삭제 버튼 -->
              <button onclick="delete_comment(this)" id="comment-delete-{{ comment.pk }}" data-freedel-id="{{ free.pk }}" data-commentdel-id="{{ comment.pk }}" class="delete-button">삭제</button>
            </div>
            <!-- comment-buttons -->
          </div>
          <!-- comment-title -->

          <!-- 댓글 수정창 -->
          <div id="form-comment-update-{{ comment.pk }}" style="display:none;">
            <textarea name="input-{{comment.pk}}" cols="10" rows="1" class="form-control" placeholder="" required="" id="input-{{comment.pk}}">{{comment.content}}</textarea>
            <button onclick="ok_function(this)" id="okBtn-{{ comment.pk }}" data-freeup-id="{{ free.pk }}" data-commentup-id="{{ comment.pk }}" class="update-button">확인</button>
          </div>

          <!-- 댓글 본문 -->
          <p id="comment-contents-{{comment.pk}}" class="comment-contents">{{ comment.content|linebreaksbr }}</p>

          <!-- 답글 버튼 -->
          <div class="button-count">
            <button onclick="recomment_create_comment(this)" id='recomment-create-{{ comment.pk }}' data-freerec-id="{{ free.pk }}" data-recommentcre-id="{{ comment.pk }}" class="recomment-button">답글</button>
            <p class="comment-count">{{comment.free_comment_user.count}}</p>
          </div>

          <!-- 답글창 -->
          <div id='form-recomment-create-{{ comment.pk }}' class="recomment-form" style='display:none;'>
            <form id="recomment-form-{{ comment.pk }}" data-freerec-id="{{ free.pk }}">
              <div class="mb-3">
                <textarea name="body" cols="40" rows="1" class="form-control" maxlength="200" placeholder="답글을 남겨보세요!
답글이 길어질 땐 답글창을 늘려보세요." required="" id="id_body"></textarea>
              </div>
            </form>

            <!-- 답글 등록 버튼 -->
            <div class="sb-div">
              <button onclick="answer(this)" id="answer-{{ comment.pk }}" data-freerec-id="{{ free.pk }}" data-commentrec-id="{{ comment.pk }}" class="recomment-submit-button">등록</button>
            </div>
          </div>
          <!-- recomment-form -->

          <!-- 답글 -->
          <div id="re-{{comment.pk}}" class="recomments">
            {% for recom in comment.free_comment_user.all %}

              <div class="user-delete">
                <!-- 닉네임 -->
                <p class="comment-user">익명{{ recom.user.pk }}</p>

                <!-- 답글 삭제 -->
                {% if user == recom.user %}
                  <button onclick="redelete_comment(this)" id="recomment-delete-{{recom.pk}}" data-recommentdel-id="{{recom.pk}}" data-recommentparentdel-id="{{ comment.pk }}" data-freeredel-id="{{ free.pk }}" class="delete-button">삭제</button>
                {% endif %}
              </div>

              <!-- 답글 내용 -->
              <p>{{ recom.body }}</p>
            {% endfor %}
          </div>
          <!-- recomments -->

          <!-- 댓글 작성자가 아니라면 수정/삭제 버튼이 안 보임 -->
        {% else %}
          <div class="user-date">
            <!-- 작성자 -->
            <p class="comment-user">익명{{ comment.user.pk}}</p>
            <!-- 작성일자 -->
            <p class="date">{{comment.updated_at}}</p>
          </div>

          <!-- 댓글 본문 -->
          <p id="comment-contents-{{comment.pk}}" class="comment-contents">{{ comment.content|linebreaksbr }}</p>

          <!-- 답글 버튼 -->
          <div class="button-count">
            <button onclick="recomment_create_comment(this)" id='recomment-create-{{ comment.pk }}' data-freerec-id="{{ free.pk }}" data-recommentcre-id="{{ comment.pk }}" class="recomment-button">답글</button>
            <p class="comment-count">{{comment.free_comment_user.count}}</p>
          </div>

          <!-- 답글창 -->
          <div id='form-recomment-create-{{ comment.pk }}' class="recomment-form" style='display:none;'>
            <form id="recomment-form-{{ comment.pk }}" data-freerec-id="{{ free.pk }}">
              <div class="mb-3">
                <textarea name="body" cols="40" rows="1" class="form-control" maxlength="200" placeholder="답글을 남겨보세요!
답글이 길어질 땐 답글창을 늘려보세요." required="" id="id_body"></textarea>
              </div>
            </form>

            <!-- 답글 등록 버튼 -->
            <div class="sb-div">
              <button onclick="answer(this)" id="answer-{{ comment.pk }}" data-freerec-id="{{ free.pk }}" data-commentrec-id="{{ comment.pk }}" class="recomment-submit-button">등록</button>
            </div>
          </div>
          <!-- recomment-form -->

          <!-- 답글 -->
          <div id="re-{{comment.pk}}" class="recomments">
            {% for recom in comment.free_comment_user.all %}

              <div class="user-delete">
                <!-- 닉네임 -->
                <p class="comment-user">익명{{ recom.user.pk }}</p>

                <!-- 답글 삭제 -->
                {% if user == recom.user %}
                  <button onclick="redelete_comment(this)" id="recomment-delete-{{recom.pk}}" data-recommentdel-id="{{recom.pk}}" data-recommentparentdel-id="{{ comment.pk }}" data-freeredel-id="{{ free.pk }}" class="delete-button">삭제</button>
                {% endif %}
              </div>

              <!-- 답글 내용 -->
              <p>{{ recom.body }}</p>
            {% endfor %}
          </div>
          <!-- recomments -->
        {% endif %}
        <!-- % if request.user.is_authenticated % -->

        <hr class="comment-divider">

        <!-- 등록된 댓글이 없을 경우 -->
        {% empty %}
        <p id="comment_empty" class="no-comment">등록된 댓글이 없습니다.<br>첫 댓글의 주인공이 되어보세요!</p>
      {% endfor %}
      <!-- % for comment in comments % -->
    </div>
    <!-- comments -->
  </div>
  <!-- detail-container -->
{% endblock %}

{% block js %}
  <script src="{% static 'js/mde/js/jquery.min.js' %}"></script>
  <script src="{% static 'js/mde/js/lib/marked.min.js' %}"></script>
  <script src="{% static 'js/mde/js/editormd.min.js' %}"></script>
  <script src="{% static 'js/mde/js/lib/prettify.min.js' %}"></script>
  <script src="{% static 'js/mde/js/lib/raphael.min.js' %}"></script>
  <script src="{% static 'js/mde/js/lib/underscore.min.js' %}"></script>
  <script src="{% static 'js/mde/js/lib/sequence-diagram.min.js' %}"></script>
  <script src="{% static 'js/mde/js/lib/flowchart.min.js' %}"></script>
  <script src="{% static 'js/mde/js/lib/jquery.flowchart.min.js' %}"></script>
  <script>
    $(function () {
      // js markdown
      editormd.markdownToHTML("content", {
        emoji: true,
        taskList: true,
        tex: true,
        flowChart: true,
        sequenceDiagram: true
      });
      $(".reference-link").each(function (i, obj) {})
    })
  </script>

  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script src="{% static 'free/js/detail.js' %}"></script>
{% endblock js %}

free/templates/free/fail.html
{% extends 'base.html' %}

{% load django_bootstrap5 %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'free/css/fail.css' %}">
{% endblock css %}

{% block content %}
<div class="fail-container">
  <img src="https://cdn-icons-png.flaticon.com/512/16/16354.png" alt="경고 이미지">
  <p class="deleted">삭제된 게시글입니다.</p>
  <button type="button" onclick="location.href='{% url 'free:index' %}'">돌아가기</button>
</div>
{% endblock content %}

free/templates/free/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'free/css/update.css' %}">
{% endblock css %}

{% block content %}
<div class="update-container">
  <p class="title">
    <a href="{% url 'free:index' %}">COMMUNITY BOARD</a><br><span class="state-change">UPDATE</span>
  </p>
  <form action='' method='POST' enctype='multipart/form-data'>
    {% csrf_token %}
    {{ free_form.media }}
    {{ free_form.as_p }}
    <div class="buttons">
      <input type="submit" value="수정" class="edit-button">
      <a href="{% url 'free:detail' free.pk %}" class="back-button">취소</a>
    </div>
  </form>
</div> <!-- update-container -->
{% endblock %}