SS/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", views.main, name="main"),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("articles/", include("articles.urls")),
    path("gathering/", include("gathering.urls")),
    path("free/", include("free.urls")),
    path("notices/", include("notices.urls")),
    path("search/", views.search, name="search"),
    path("calendars/", include("calendars.urls")),
    path("mdeditor/", include("mdeditor.urls")),
    path("notes/", include("notes.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("<int:pk>/detail/", views.detail, name="detail"),
    path("<int:pk>/edit_profile/", views.edit_profile, name="edit_profile"),
    path("<int:pk>/password/", views.change_password, name="change_password"),
    path("<int:pk>/follow/", views.follow, name="follow"),
    path("<int:pk>/message/", views.message, name="message"),
    path("login/github", views.social_signup_request, name="social"),
    path("login/github/callback", views.social_signup_callback),
    path("<int:pk>/send/", views.send, name="send"),
    path("<int:pk>/message_delete/", views.message_delete, name="message_delete"),
]

gathering/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = "gathering"

urlpatterns = [
    path("list/", views.gathering_list, name="gathering-list"),
    path("create/", views.gathering_create, name="gathering-create"),
    path("<int:gathering_id>/", views.gathering_detail, name="gathering-detail"),
    path("edit/<int:gathering_id>/", views.gathering_edit, name="gathering-edit"),
    path("delete/<int:gathering_id>/", views.gathering_delete, name="gathering-delete"),
    path("end/<int:gathering_id>/", views.end_gathering, name="end_gathering"),
    path("edit/<int:gathering_id>/choice/add/", views.add_choice, name="add_choice"),
    path("edit/choice/<int:choice_id>/", views.choice_edit, name="choice_edit"),
    path("delete/choice/<int:choice_id>/", views.choice_delete, name="choice_delete"),
    path("<int:gathering_id>/vote/", views.gathering_vote, name="vote"),
    path("fail/", views.fail, name="fail"),
    # 검색
    path("study/", views.study, name="study"),
    path("moim/", views.moim, name="moim"),
    # 댓글
    path("<int:gathering_pk>/comments_create/", views.comment_create, name="comment_create"),
    path("<int:gathering_pk>/comment_delete/<int:comment_pk>/delete/",views.comment_delete,name="comment_delete"),
    path("<int:gathering_pk>/comment_update/<int:comment_pk>/update/",views.comment_update,name="comment_update"),
    path("<int:gathering_pk>/recomment_create/<int:comment_pk>/", views.recomment_create, name='recomment_create'),
    path("<int:gathering_pk>/recomment_delete/<int:comment_pk>/delete/<int:recomment_pk>/", views.recomment_delete, name="recomment_delete"),
    path("<int:gathering_pk>/like/", views.like, name="like"),
    path("meeting_offline/", views.meeting_offline, name="meeting_offline"),
    path("search/", views.search, name="search"),
]

gathering/models.py
from django.db import models
from SS.settings import AUTH_USER_MODEL
from django.utils import timezone

# Create your models here.


class Gatherings(models.Model):
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=30)
    content = models.TextField()

    Moim = "모임"
    Study = "스터디"
    CATEGORIES = [
        (None, "모집유형을 선택해주세요."),
        (Moim, "모임"),
        (Study, "스터디"),
    ]

    category = models.CharField(
        choices=CATEGORIES, max_length=10, default="모집유형을 선택해주세요."
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_users = models.ManyToManyField(AUTH_USER_MODEL, related_name="like_gathering")
    hits = models.PositiveIntegerField(default=0, verbose_name="조회수")
    q = models.CharField(max_length=50, default="모임")

    pub_date = models.DateTimeField(default=timezone.now)
    active = models.BooleanField(default=True)

    def user_can_vote(self, user):
        user_votes = user.vote_set.all()
        qs = user_votes.filter(gathering=self)
        if qs.exists():
            return False
        return True

    @property
    def get_vote_count(self):
        return self.vote_set.count()

    def get_result_dict(self):
        res = []
        dic = []
        cnt = 0
        for choice in self.choice_set.all():
            d = {}
            d["title"] = choice.choice_text
            d["num_votes"] = choice.get_vote_count
            d["pk"] = choice.pk
            if choice.vote_set.all():
                for i in choice.vote_set.all():
                    print(cnt)
                    d[str(cnt)] = i
                    cnt += 1

                    
            if not self.get_vote_count:
                d["percentage"] = 0
            else:
                d["percentage"] = (choice.get_vote_count / self.get_vote_count) * 100

            res.append(d)
        dic.append(res)
        return res

    def get_result_first(self):
        result = []
        for choice in self.choice_set.all():
            d = {}
            d["title"] = choice.choice_text
            d["num_votes"] = choice.get_vote_count

            result.append(d)
        result = sorted(result, key=lambda x: x["num_votes"], reverse=True)
        max = result[0]["num_votes"]

        title = []
        for res in result:
            if res["num_votes"] == max:
                title.append(res["title"])

        return title

    def __str__(self):
        return self.title


class GatheringsComment(models.Model):
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    gathering = models.ForeignKey(
        Gatherings, on_delete=models.CASCADE, related_name="gatheringcomments"
    )
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class ReComment3(models.Model):
    comment = models.ForeignKey(
        GatheringsComment,
        on_delete=models.CASCADE,
        related_name="gatherings_comment_user",
    )
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    body = models.CharField("답글", max_length=200)
    updated_at = models.DateTimeField(auto_now=True)


class Choice(models.Model):
    gathering = models.ForeignKey(Gatherings, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=255)

    @property
    def get_vote_count(self):
        return self.vote_set.count()

    def __str__(self):
        return f"{self.gathering.title[:25]} - {self.choice_text[:25]}"


class Vote(models.Model):
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    gathering = models.ForeignKey(Gatherings, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.username}"

gathering/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.db.models import Count, Q
from django.core.paginator import Paginator
from django.contrib import messages
from accounts.models import User, Notification
from gathering.models import Gatherings, Choice, Vote, GatheringsComment, ReComment3
from gathering.forms import (
    GatheringsAddForm,
    EditGatheringsForm,
    ChoiceAddForm,
    CommentForm,
    ReCommentForm,
)
from django.http import JsonResponse
from datetime import date, datetime, timedelta
import json

# Create your views here.


def maketable(p):
    table = [0] * len(p)
    i = 0
    for j in range(1, len(p)):
        while i > 0 and p[i] != p[j]:
            i = table[i - 1]
        if p[i] == p[j]:
            i += 1
            table[j] = i
    return table


def KMP(p, t):
    ans = []
    table = maketable(p)
    i = 0
    for j in range(len(t)):
        while i > 0 and p[i] != t[j]:
            i = table[i - 1]
        if p[i] == t[j]:
            if i == len(p) - 1:
                ans.append(j - len(p) + 2)
                i = table[i]
            else:
                i += 1
    return ans


def gathering_list(request):
    all_gathering = Gatherings.objects.all().order_by("-created_at")

    page = request.GET.get("page", "1")
    paginator = Paginator(all_gathering, 9)
    page_obj = paginator.get_page(page)
    context = {
        "all_gatherings": all_gathering,
        "page_obj": page_obj,
    }
    return render(request, "gathering/gathering_list.html", context)


@login_required
def gathering_create(request):
    if request.method == "POST":
        form = GatheringsAddForm(request.POST)
        if form.is_valid():
            gathering = form.save(commit=False)
            gathering.user = request.user
            gathering.save()
            new_choice1 = Choice(
                gathering=gathering, choice_text=form.cleaned_data["choice1"]
            ).save()

            new_choice2 = Choice(
                gathering=gathering, choice_text=form.cleaned_data["choice2"]
            ).save()

            return redirect("gathering:gathering-list")
    else:
        form = GatheringsAddForm()
    context = {
        "form": form,
    }
    return render(request, "gathering/gathering_create.html", context)


def gathering_detail(request, gathering_id):
    gathering = get_object_or_404(Gatherings, id=gathering_id)
    user = User.objects.get(pk=request.user.pk)
    comments = GatheringsComment.objects.filter(gathering_id=gathering_id).order_by(
        "-pk"
    )
    comment_form = CommentForm()
    comment_form.fields["content"].widget.attrs[
        "placeholder"
    ] = "댓글을 남겨주세요!\n댓글이 길어질 땐 댓글창을 늘려보세요."
    for i in comments:
        i.updated_at = i.updated_at.strftime("%y-%m-%d")
        with open("filtering.txt", "r", encoding="utf-8") as txtfile:
            for word in txtfile.readlines():
                word = word.strip()
                ans = KMP(word, i.content)
                if ans:
                    for k in ans:
                        k = int(k)
                        if k < len(i.content) // 2:
                            i.content = (
                                len(i.content[k - 1 : len(word)]) * "*"
                                + i.content[len(word) :]
                            )
                        else:
                            i.content = (
                                i.content[0 : k - 1] + len(i.content[k - 1 :]) * "*"
                            )
    if request.user.is_authenticated:
        new_message = Notification.objects.filter(Q(user_id=user.pk) & Q(check=False))
        message_count = len(new_message)
    loop_count = gathering.choice_set.count()
    context = {
        "gathering": gathering,
        "loop_time": range(0, loop_count),
        "comments": comments,
        "comment_form": comment_form,
        "count": message_count,
    }
    if not gathering.active:
        response = render(request, "gathering/gathering_result.html", context)
    else:
        response = render(request, "gathering/gathering_detail.html", context)
    expire_date, now = datetime.now(), datetime.now()
    expire_date += timedelta(days=1)
    expire_date = expire_date.replace(hour=0, minute=0, second=0, microsecond=0)
    expire_date -= now
    max_age = expire_date.total_seconds()

    cookievalue = request.COOKIES.get("hitgathering", "")

    if f"{gathering_id}" not in cookievalue:
        cookievalue += f"{gathering_id}"
        response.set_cookie(
            "hitgathering", value=cookievalue, max_age=max_age, httponly=True
        )
        gathering.hits += 1
        gathering.save()
    return response


@login_required
def add_choice(request, gathering_id):
    gathering = get_object_or_404(Gatherings, pk=gathering_id)
    if request.user != gathering.user:
        return redirect("gathering:gathering-list")

    if request.method == "POST":
        form = ChoiceAddForm(request.POST)
        if form.is_valid:
            new_choice = form.save(commit=False)
            new_choice.gathering = gathering
            new_choice.save()
            messages.success(
                request,
                "선택사항이 추가되었습니다.",
                extra_tags="alert alert-success alert-dismissible fade show",
            )
            return redirect("gathering:gathering-edit", gathering.id)
    else:
        form = ChoiceAddForm()
    context = {
        "form": form,
    }
    return render(request, "gathering/add_choice.html", context)


# 게시글 수정 페이지
@login_required
def gathering_edit(request, gathering_id):
    gathering = get_object_or_404(Gatherings, pk=gathering_id)
    if request.user != gathering.user:
        return redirect("gathering:gathering-list")
    if request.method == "POST":
        form = EditGatheringsForm(request.POST, instance=gathering)
        if form.is_valid:
            form.save()
            return redirect("gathering:gathering-detail", gathering.id)
    else:
        form = EditGatheringsForm(instance=gathering)
        form_choice = ChoiceAddForm()
        form_edit = []
        for choice in gathering.choice_set.all():
            form_edit.append([choice, ChoiceAddForm(instance=choice)])

    return render(
        request,
        "gathering/gathering_edit.html",
        {
            "form": form,
            "gathering": gathering,
            "form_choice": form_choice,
            "form_edit": form_edit,
        },
    )


@login_required
def choice_edit(request, choice_id):
    choice = get_object_or_404(Choice, pk=choice_id)
    gathering = get_object_or_404(Gatherings, pk=choice.gathering.id)
    if request.user != gathering.user:
        return redirect("gathering:gathering-list")
    if request.method == "POST":
        form = ChoiceAddForm(request.POST, instance=choice)
        if form.is_valid:
            new_choice = form.save(commit=False)
            new_choice.gathering = gathering
            new_choice.save()
            messages.success(
                request,
                "선택사항이 업데이트 되었습니다.",
                extra_tags="alert alert-success alert-dismissible fade show",
            )
            return redirect("gathering:gathering-edit", gathering.id)
    else:
        form = ChoiceAddForm(instance=choice)
    context = {
        "form": form,
        "edit_choice": True,
        "choice": choice,
    }
    return render(request, "gathering/add_choice.html", context)


@login_required
def gathering_delete(request, gathering_id):
    gathering = get_object_or_404(Gatherings, pk=gathering_id)
    if request.user != gathering.user:
        return redirect("gathering:gathering-list")
    gathering.delete()
    messages.success(
        request,
        "투표가 완료되었습니다.",
        extra_tags="alert alert-success alert-dismissible fade show",
    )
    return redirect("gathering:gathering-list")


@login_required
def choice_delete(request, choice_id):
    choice = get_object_or_404(Choice, pk=choice_id)
    gathering = get_object_or_404(Gatherings, pk=choice.gathering.id)
    if request.user != gathering.user:
        return redirect("gathering:gathering-list")
    choice.delete()
    messages.success(
        request,
        "선택사항이 삭제되었습니다.",
        extra_tags="alert alert-success alert-dismissible fade show",
    )
    return redirect("gathering:gathering-edit", gathering.id)


@login_required
def gathering_vote(request, gathering_id):
    gathering = get_object_or_404(Gatherings, pk=gathering_id)
    choice_id = request.POST.get("choice")
    comments = GatheringsComment.objects.filter(gathering_id=gathering_id).order_by(
        "-pk"
    )
    comment_form = CommentForm()
    comment_form.fields["content"].widget.attrs[
        "placeholder"
    ] = "댓글을 남겨주세요!\n댓글이 길어질 땐 댓글창을 늘려보세요."
    if not gathering.user_can_vote(request.user):
        messages.error(
            request,
            "이미 투표하셨습니다!",
            extra_tags="alert alert-warning alert-dismissible fade show",
        )
        return redirect("gathering:gathering-detail", gathering_id)

    elif choice_id:
        choice = Choice.objects.get(id=choice_id)
        vote = Vote(user=request.user, gathering=gathering, choice=choice)
        vote.save()
        context = {
            "gathering": gathering,
            "comments": comments,
            "comment_form": comment_form,
        }
        return render(request, "gathering/gathering_result.html", context)
    else:
        messages.error(
            request,
            "선택 후 투표 부탁드립니다",
            extra_tags="alert alert-warning alert-dismissible fade show",
        )
        return redirect("gathering:gathering-detail", gathering_id)


@login_required
def end_gathering(request, gathering_id):
    gathering = get_object_or_404(Gatherings, pk=gathering_id)

gathering/templates/gathering/add_choice.html
{% extends 'base.html' %}

{% load static %}
{% load widget_tweaks %}
{% load django_bootstrap5 %}
{% block css %}
<link rel="stylesheet" href="{% static 'gathering/css/gathering_add_choice.css' %}">
<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
<link rel="icon" href="/favicon.ico" type="image/x-icon">
{% endblock css %}
{% block content %}
<div class="container">
    <div class="row center">
        <div class="col-md-6 offset-md-3">
            {% if edit_choice %}
            <h3>선택지 수정하기</h3>
            {% else %}
            <h3>선택지 추가하기</h3>
            {% endif %}
         
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.choice_text|attr:"placeholder:추가선택" }}
                {% if edit_choice %}
                <div class="buttons">
                    <button type="submit" class="btn" id="update">업데이트</button>
                    <a class="btn btn-danger" href="{% url 'gathering:choice_delete' choice.id %}" role="button" onclick="return confirm('해당 선택지를 지우시겠습니까?')" id="delete">삭제</a>
                    {% else %}
                    <button type="submit" class="btn" id="add">추가하기</button>
                    {% endif %}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

gathering/templates/gathering/fail.html
{% extends 'base.html' %}

{% load django_bootstrap5 %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'gathering/css/fail.css' %}">
{% endblock css %}

{% block content %}
<div class="fail-container">
  <img src="https://cdn-icons-png.flaticon.com/512/16/16354.png" alt="경고 이미지">
  <p class="deleted">삭제된 게시글입니다.</p>
  <button type="button" onclick="location.href='{% url 'gathering:gathering-list' %}'">돌아가기</button>
</div>
{% endblock content %}

gathering/templates/gathering/gathering_list.html
{% extends 'base.html' %}
{% load django_bootstrap5%}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static 'gathering/css/gathering_list.css' %}">
  <link rel="stylesheet" href="{% static 'gathering/css/gathering_list2.css' %}">
  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
  <link rel="icon" href="/favicon.ico" type="image/x-icon">
{% endblock css %}
{% block content %}
  <!--클릭 시 링크 설정-->
  <div class="container total">
    <p class="main_title">GATHERING BOARD</p>
    <ul class="menu__tabs">
      <li>
        <a id="모임" href="{% url 'gathering:moim' %}">
          <i class="bi bi-people-fill"></i>모임</a>
      </li>
      <li>
        <a id="스터디" href="{% url 'gathering:study' %}">
          <i class="bi bi-book"></i>스터디</a>
      </li> 
       {% comment %} <div class="d-flex ">
      <button><a href="{% url 'gathering:moim' %}">
        <i class="bi bi-people-fill"></i>모임</a></button>
      <button> <a href="{% url 'gathering:study' %}">
        <i class="bi bi-book"></i>스터디</a></button>  {% endcomment %}
        
      <div class="writing_button">
        <button type="button" class="create-button" onclick="location.href='{% url 'gathering:gathering-create' %}'">글쓰기</button>
      </div>
     </ul> 

    <!-- 서치창 -->
    <div class="d-flex justify-content-end">
      <div class="search-box">
        <form role="search" class="search-txt" action="{% url 'gathering:search' %}">
          <input type="search" class="search-txt" name="search" placeholder="닉네임, 제목, 내용을 검색해보세요.">
          <button class="search-btn" type="submit"><i class="bi bi-search"></i></button>
        </form>
      </div>
      </div>

    <hr>
    <div id="gathering" class="option-active ">
    {% for gathering in page_obj %}
        <div class="card">
          <div class="total-card">
            <div class="card-header">
              <h1 class="small_title">{{ gathering.title }}</h1>
            </div>
            <div class="card-body">
              <div class="card-header-is_closed">
                <div class="card-header-text">
                  {% if gathering.active %}
                    {% if request.user == gathering.user %}

                    <a href="{% url 'gathering:end_gathering' gathering.id %}"  data-toggle="tooltip" data-placement="top" title="투표종료"
                        onclick="return confirm('모집을 완료하시겠습니까?')" id="end" class="end">마감<br>하기</a>
                    {% elif request.user != gathering.user %}
                      모집중
                    {% endif %}
                  {% else %}
                    <div class="complete_">
                      <span class="complete">마감</span>
                    </div>
                  {% endif %}
                </div>
                <!-- <div class="card-header-number">{{ gathering.get_vote_count }} / ?</div> -->
              </div>
              <div class="card-body-header">
                <p>
                  <span class="card-body-hashtag">#{{gathering.category}}</span></p>
                <!-- <p class="hiding">hiding text</p> -->
                <span class="card-body-nickname" id="username">
                  <i class="bi bi-person"></i>{{ gathering.user.nickname }}</span>
              </div>
              <div class="card-body-description">
                <p class="gathering_content scroll">
                  {{ gathering.content }}
                </p>
                <div class="btn-more">
                  <button class="custom-btn btn-6">
                    <span>
                      <a href="{% url 'gathering:gathering-detail' gathering.id %}" class="more">더보기</a></span></button>
                </div>
              </div>
            </div>
            <div class="card-body-footer">
              <div>
                <i class="reg_date">
                  {{gathering.created_at|date:"Y년 m월 d일"}}</i>
              </div>
              <div>
                <i class="bi bi-eye">
                  <span class="eye">{{gathering.hits}}</span></i>
                <i class="bi bi-chat-dots">
                  <span class="chat">{{gathering.gatheringcomments.count}}</span></i>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
      </div>

      <div id="study" class="option-active">
      {% for gathering in question_list %}
        {% if gathering.category == "스터디" %}
          <div class="card">
            <div class="total-card">
              <div class="card-header">
                <h1 class="small_title">{{ gathering.title }}</h1>
              </div>
              <div class="card-body">
                <div class="card-header-is_closed">
                  <div class="card-header-text">
                    {% if gathering.active %}
                      {% if request.user == gathering.user %}
                        <a href="{% url 'gathering:end_gathering' gathering.id %}" data-toggle="tooltip" data-placement="top" title="투표종료" onclick="return confirm('모집을 완료하시겠습니까?')" id="end">마감<br>하기</a>
                      {% elif request.user != gathering.user %}
                        모집중
                      {% endif %}
                    {% else %}
                      <div class="complete_">
                        <span class="complete">완료됨</span>
                      </div>
                    {% endif %}
                  </div>
                  <!-- <div class="card-header-number">{{ gathering.get_vote_count }} / ?</div> -->
                </div>
                <div class="card-body-header">
                  <p>
                    <span class="card-body-hashtag">#{{gathering.category}}</span></p>
                  <!-- <p class="hiding">hiding text</p> -->
                  <span class="card-body-nickname" id="username">
                    <i class="bi bi-person"></i>{{ gathering.user.nickname }}</span>
                </div>
                <div class="card-body-description">
                  <p class="gathering_content scroll">
                    {{ gathering.content }}
                  </p>
                  <div class="btn-more">
                    <button class="custom-btn btn-6">
                      <span>
                        <a href="{% url 'gathering:gathering-detail' gathering.id %}" class="more ">더보기</a></span></button>
                  </div>
                </div>
              </div>
              <div class="card-body-footer">
                <div>
                  <i class="reg_date">
                    {{gathering.created_at|date:"Y년 m월 d일"}}</i>
                </div>
                <div>
                  <i class="bi bi-eye">
                    <span class="eye">{{gathering.hits}}</span></i>
                  <i class="bi bi-chat-dots">
                    <span class="chat">{{gathering.gatheringcomments.count}}</span></i>
                </div>
              </div>
            </div>
          </div>
          {%endif%}
        {% endfor %}
        </div>

        <ul class="pagination justify-content-center">
          <!-- 이전페이지 -->
          {% if page_obj.has_previous %}
            <li class="page-item">
              <a class="page-link " href="?page={{ page_obj.previous_page_number }}">〈</a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <a class="page-link" tabindex="-1" aria-disabled="true" href="#">〈</a>
            </li>
          {% endif %}
          <!-- 페이지리스트 -->
          {% for page_number in page_obj.paginator.page_range %}
            {% if page_number >= page_obj.number|add:-5 and page_number <= page_obj.number|add:5 %}
              {% if page_number == page_obj.number %}
                <li class="page-item active" aria-current="page">
                  <a class="page-link " href="?page={{ page_number }}">{{ page_number }}</a>
                </li>
              {% else %}
                <li class="page-item">
                  <a class="page-link " href="?page={{ page_number }}">{{ page_number }}</a>
                </li>
              {% endif %}
            {% endif %}
          {% endfor %}
          <!-- 다음페이지 -->
          {% if page_obj.has_next %}
            <li class="page-item">
              <a class="page-link " href="?page={{ page_obj.next_page_number }}">〉</a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <a class="page-link" tabindex="-1" aria-disabled="true" href="#">〉</a>
            </li>
          {% endif %}
        </ul>
        <!-- pagination -->
      </div>

    {% endblock content %}
    {% block js %}
      <script src="http://code.jquery.com/jquery-latest.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
      <script src="{% static 'gathering/js/list.js' %}"></script>
    {% endblock js %}