SS/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", views.main, name="main"),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("articles/", include("articles.urls")),
    path("gathering/", include("gathering.urls")),
    path("free/", include("free.urls")),
    path("notices/", include("notices.urls")),
    path("search/", views.search, name="search"),
    path("calendars/", include("calendars.urls")),
    path("mdeditor/", include("mdeditor.urls")),
    path("notes/", include("notes.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    # 질문게시글
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:articles_pk>/", views.detail, name="detail"),
    path("<int:articles_pk>/update/", views.update, name="update"),
    path("<int:articles_pk>/delete/", views.delete, name="delete"),
    path("fail/", views.fail, name="fail"),
    # 댓글
    path("<int:articles_pk>/comment_create/", views.comment_create, name="comment_create"),
    path("<int:articles_pk>/comment_delete/<int:comment_pk>/delete/",views.comment_delete,name="comment_delete",),
    path("<int:articles_pk>/comment_update/<int:comment_pk>/update/",views.comment_update,name="comment_update",),
    path("<int:articles_pk>/recomment_create/<int:comment_pk>/", views.recomment_create, name='recomment_create'),
    path("<int:articles_pk>/recomment_delete/<int:comment_pk>/delete/<int:recomment_pk>/", views.recomment_delete, name="recomment_delete"),
    path("<int:articles_pk>/like/", views.like, name="like"),
    path("search/", views.search, name="search"),
]

free/urls.py
from django.urls import path
from . import views

app_name = "free"

urlpatterns = [
    # 자유게시글
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:free_pk>/", views.detail, name="detail"),
    path("<int:free_pk>/update/", views.update, name="update"),
    path("<int:free_pk>/delete/", views.delete, name="delete"),
    path("fail/", views.fail, name="fail"),
    # 댓글
    path("<int:free_pk>/comments_create/", views.comment_create, name="comment_create"),
    path("<int:free_pk>/comment_delete/<int:comment_pk>/delete/",views.comment_delete,name="comment_delete"),
    path("<int:free_pk>/comment_update/<int:comment_pk>/update/",views.comment_update,name="comment_update"),
    path("<int:free_pk>/recomment_create/<int:comment_pk>/", views.recomment_create, name='recomment_create'),
    path("<int:free_pk>/recomment_delete/<int:comment_pk>/delete/<int:recomment_pk>/", views.recomment_delete, name="recomment_delete"),
    path("<int:free_pk>/like/", views.like, name="like"),
    path("search/", views.search, name="search"),
]

articles/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from mdeditor.fields import MDTextField

# Create your models here.


class Articles(models.Model):
    check = models.BooleanField(default=False)
    title = models.CharField(max_length=50, verbose_name="Title")
    category_position = [
        (None, "질문유형을 선택해주세요."),
        ("CS", "CS"),
        ("알고리즘", "알고리즘"),
        ("진로", "진로"),
        ("오류", "오류"),
        ("기타", "기타"),
    ]
    category = models.CharField(
        max_length=50, choices=category_position, default="질문유형을 선택해주세요."
    )
    create_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    content = MDTextField()
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_articles"
    )
    unname = models.BooleanField(default=False)
    hits = models.PositiveIntegerField(default=0, verbose_name="조회수")
    q = models.CharField(max_length=50, default="질문")


class Photo(models.Model):
    article = models.ForeignKey(Articles, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="images/", blank=True)


class Comment(models.Model):
    content = models.TextField()
    articles = models.ForeignKey(
        Articles, on_delete=models.CASCADE, related_name="comment_user"
    )
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    unname = models.BooleanField(default=False)


class ReComment2(models.Model):
    comment = models.ForeignKey(
        Comment, on_delete=models.CASCADE, related_name="article_comment_user"
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    body = models.CharField("답글", max_length=200)
    updated_at = models.DateTimeField(auto_now=True)
    unname = models.BooleanField(default=False)

articles/forms.py
from django import forms
from .models import Articles, Comment, ReComment2, Photo
from django.forms import ClearableFileInput


class ArticlesForm(forms.ModelForm):
    class Meta:
        model = Articles
        fields = [
            "category",
            "title",
            "content",
            "unname",
        ]
        widgets = {
            "title": forms.TextInput(
                attrs={
                    "placeholder": "제목을 입력해주세요.",
                },
            ),
            "content": forms.Textarea(attrs={"class": "form-control", "rows": 10}),
        }
        labels = {
            "category": "",
            "title": "",
            "unname": "익명 선택 ",
            "content": "",
        }


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = [
            "image",
        ]
        widgets = {
            "image": ClearableFileInput(attrs={"multiple": True}),
        }
        labels = {
            "image": "이미지를 선택해주세요.",
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = {
            "content",
            "unname",
        }
        widgets = {
            "content": forms.Textarea(attrs={"class": "form-control", "rows": 1}),
        }
        labels = {
            "unname": "익명 선택",
        }


class ReCommentForm(forms.ModelForm):
    class Meta:
        model = ReComment2
        fields = [
            "body",
            "unname",
        ]
        widgets = {
            "body": forms.Textarea(attrs={"class": "form-control", "rows": 1}),
        }
        labels = {
            "unname": "익명 선택",
        }

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from .forms import ArticlesForm, CommentForm, ReCommentForm, PhotoForm
from accounts.models import User, Notification
from django.db.models import Count
from django.db.models import Q
from datetime import date, datetime, timedelta
import json
from django.core.paginator import Paginator

# Create your views here.
def maketable(p):
    table = [0] * len(p)
    i = 0
    for j in range(1, len(p)):
        while i > 0 and p[i] != p[j]:
            i = table[i - 1]
        if p[i] == p[j]:
            i += 1
            table[j] = i
    return table


def KMP(p, t):
    ans = []
    table = maketable(p)
    i = 0
    for j in range(len(t)):
        while i > 0 and p[i] != t[j]:
            i = table[i - 1]
        if p[i] == t[j]:
            if i == len(p) - 1:
                ans.append(j - len(p) + 2)
                i = table[i]
            else:
                i += 1
    return ans


def index(request):
    articles = Articles.objects.order_by("-pk")  # 최신순으로나타내기
    page = request.GET.get("page", "1")
    paginator = Paginator(articles, 10)
    page_obj = paginator.get_page(page)
    if request.user.is_authenticated:
        user = User.objects.get(pk=request.user.pk)
        new_message = Notification.objects.filter(Q(user=user.pk) & Q(check=False))
        message_count = len(new_message)
        context = {
            "articles": articles,
            "count": message_count,
            "question_list": page_obj,
        }
    else:
        context = {"articles": articles, "question_list": page_obj}
    return render(request, "articles/index.html", context)


@login_required
def create(request):
    if request.user.is_authenticated:
        user = User.objects.get(pk=request.user.pk)
        new_message = Notification.objects.filter(Q(user=user.pk) & Q(check=False))
        message_count = len(new_message)
    if request.method == "POST":
        form = ArticlesForm(request.POST, request.FILES)
        photo_form = PhotoForm(request.POST, request.FILES)
        images = request.FILES.getlist("image")
        if form.is_valid() and photo_form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            if len(images):
                for image in images:
                    image_instance = Photo(article=article, image=image)
                    article.save()
                    image_instance.save()
            else:
                article.save()
            return redirect("articles:index")
    else:
        form = ArticlesForm()
        photo_form = PhotoForm()

    context = {
        "count": message_count,
        "form": form,
        "photo_form": photo_form,
    }
    return render(request, "articles/create.html", context)


@login_required
def detail(request, articles_pk):
    articles = Articles.objects.get(pk=articles_pk)
    user = User.objects.get(pk=request.user.pk)
    comments = Comment.objects.filter(articles_id=articles_pk).order_by("-pk")
    comment_form = CommentForm()
    recomment_form = ReCommentForm()
    comment_form.fields["content"].widget.attrs[
        "placeholder"
    ] = "댓글을 남겨주세요!\n댓글이 길어질 땐 댓글창을 늘려보세요."
    recomment_form.fields["body"].widget.attrs[
        "placeholder"
    ] = "답글을 남겨보세요!\n답글이 길어질 땐 답글창을 늘려보세요."

    photos = articles.photo_set.all()
    for i in comments:  # 시간바꾸는로직
        i.updated_at = i.updated_at.strftime("%Y.%m.%d. %H:%M %p")
        with open("filtering.txt", "r", encoding="utf-8") as txtfile:
            for word in txtfile.readlines():
                word = word.strip()
                ans = KMP(word, i.content)
                if ans:
                    for k in ans:
                        k = int(k)
                        if k < len(i.content) // 2:
                            i.content = (
                                len(i.content[k - 1 : len(word)]) * "*"
                                + i.content[len(word) :]
                            )
                        else:
                            i.content = (
                                i.content[0 : k - 1] + len(i.content[k - 1 :]) * "*"
                            )
    if request.user.is_authenticated:
        new_message = Notification.objects.filter(Q(user_id=user.pk) & Q(check=False))
        message_count = len(new_message)
    context = {
        "count": message_count,
        "articles": articles,
        "comment_form": comment_form,
        "recomment_form": recomment_form,
        "comments": comments,
        "photos": photos,
    }

    response = render(request, "articles/detail.html", context)

    expire_date, now = datetime.now(), datetime.now()
    expire_date += timedelta(days=1)
    expire_date = expire_date.replace(hour=0, minute=0, second=0, microsecond=0)
    expire_date -= now
    max_age = expire_date.total_seconds()

    cookievalue = request.COOKIES.get("hitreview", "")

    if f"{articles_pk}" not in cookievalue:
        cookievalue += f"{articles_pk}"
        response.set_cookie(
            "hitreview", value=cookievalue, max_age=max_age, httponly=True
        )
        articles.hits += 1
        articles.save()
    return response


@login_required
def update(request, articles_pk):
    article = Articles.objects.get(pk=articles_pk)
    user = User.objects.get(pk=request.user.pk)
    if request.user == article.user:
        photos = article.photo_set.all()
        instancetitle = article.title
        if request.method == "POST":
            form = ArticlesForm(request.POST, request.FILES, instance=article)
            if photos:
                photo_form = PhotoForm(request.POST, request.FILES, instance=photos[0])
            else:
                photo_form = PhotoForm(request.POST, request.FILES)
            images = request.FILES.getlist("image")
            for photo in photos:
                if photo.image:
                    photo.delete()
            if form.is_valid() and photo_form.is_valid():
                article = form.save(commit=False)
                article.check = True
                article.user = request.user
                if len(images):
                    for image in images:
                        image_instance = Photo(article=article, image=image)
                        article.save()
                        image_instance.save()
                else:
                    article.save()
                return redirect("articles:detail", article.pk)
        else:
            form = ArticlesForm(instance=article)
            if photos:
                photo_form = PhotoForm(instance=photos[0])
            else:
                photo_form = PhotoForm()
        if request.user.is_authenticated:
            new_message = Notification.objects.filter(
                Q(user_id=user.pk) & Q(check=False)
            )
            message_count = len(new_message)
            context = {
                "count": message_count,
                "form": form,
                "photo_form": photo_form,
                "instancetitle": instancetitle,
                "article": article,
            }
        else:
            context = {
                "form": form,
                "photo_form": photo_form,
                "instancetitle": instancetitle,
                "article": article,
            }
        return render(request, "articles/update.html", context)
    else:
        return redirect("articles:index")


@login_required
def delete(request, articles_pk):
    articles = Articles.objects.get(pk=articles_pk)
    articles.delete()
    return redirect("articles:index")


@login_required
def fail(request):
    if request.user.is_authenticated:
        user = User.objects.get(pk=request.user.pk)
        new_message = Notification.objects.filter(Q(user=user.pk) & Q(check=False))
        message_count = len(new_message)
    context = {
        "count": message_count,
    }
    return render(request, "articles/fail.html")


@login_required
def comment_create(request, articles_pk):
    articles = Articles.objects.get(pk=articles_pk)
    users = User.objects.get(pk=request.user.pk)
    comment_form = CommentForm(request.POST)
    recomment_form = ReCommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.articles = articles
        comment.user = request.user
        comment.save()
        if comment.unname:
            message = f"질문게시판 {articles.title}의 글에 {'익명' + str(users.pk)}님이 댓글을 달았습니다."
        else:
            message = f"질문게시판 {articles.title}의 글에 {users.nickname}님이 댓글을 달았습니다."
        Notification.objects.create(
            user=articles.user, message=message, category="질문", nid=articles.pk
        )
    if request.user.is_authenticated:
        user = User.objects.get(pk=request.user.pk)
        new_message = Notification.objects.filter(Q(user=user.pk) & Q(check=False))
        message_count = len(new_message)
    user = request.user.pk
    temp1 = Comment.objects.filter(articles_id=articles_pk).order_by("-pk")
    comment_data = []
    recomment_data2 = []
    for t in temp1:
        temp2 = ReComment2.objects.filter(comment_id=t.pk).order_by("-pk")
        t.updated_at = t.updated_at.strftime("%Y.%m.%d. %H:%M %p")
        with open("filtering.txt", "r", encoding="utf-8") as txtfile:
            for word in txtfile.readlines():
                word = word.strip()
                ans = KMP(word, t.content)
                if ans:
                    for k in ans:
                        k = int(k)
                        if k < len(t.content) // 2:
                            t.content = (
                                len(t.content[k - 1 : len(word)]) * "*"
                                + t.content[len(word) :]
                            )
                        else:

articles/templates/articles/create.html
{% extends 'base.html' %}
{% load django_bootstrap5%}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'articles/css/create.css' %}">
<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
<link rel="icon" href="/favicon.ico" type="image/x-icon">
{% endblock css %}


{% block content %}
<div class="create-container">
  <p class="title">
    <a href="{% url 'articles:index' %}">QUESTION BOARD</a><br><span class="state-change">CREATE</span>
  </p>
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.media }}
    <div class="mt-2">{{ form.title }}</div>
    <div class="mt-2">{{ form.category }}</div>
    <div class="mt-2">{{ form.content }}</div>
    <div class="id_unname">
    <span>익명선택 </span>
      &nbsp;{{form.unname}}
    </div>
    
      <!-- <div class="buttons">
          <button type="submit" class="submit-button">작성</button>
          <a href="{% url 'articles:index' %}" class="back-button">취소</a>   
      </div> -->
      <div class="container text-center">
        <div class="row">
      <div class="buttons">
          <div class="col-xl-2 col-lg-3 col-md-4 col-sm-6">
            <button type="submit" class="btn submit-button" id="submit_btn">작성</button>
          </div>
          <div class="col-xl-2 col-lg-3 col-md-4 col-sm-6">
          <button id="cancel_btn"><a href="{% url 'articles:index' %}" class="btn cancel_btn" >취소</a></button>
          </div>
        </div>  
        </div>
      </div>
    
  </form>
</div>
{% endblock content %}

{% block js %}
{% endblock js %}

articles/templates/articles/fail.html
{% extends 'base.html' %}

{% load django_bootstrap5 %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'articles/css/fail.css' %}">
{% endblock css %}

{% block content %}
<div class="fail-container">
  <img src="https://cdn-icons-png.flaticon.com/512/16/16354.png" alt="경고 이미지">
  <p class="deleted">삭제된 게시글입니다.</p>
  <button type="button" onclick="location.href='{% url 'articles:index' %}'">돌아가기</button>
</div>
{% endblock content %}

articles/templates/articles/index.html
{% extends 'base.html' %}
{% load django_bootstrap5%}
{% load static %}

{% block css %}
  <link rel="stylesheet" href="{% static 'articles/css/index.css' %}">
  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
  <link rel="icon" href="/favicon.ico" type="image/x-icon">
{% endblock css %}

{% block content %}
  <div class="index-container">
    <p class="title">QUESTION BOARD</p>
   
  <div class="search-create">
    <!-- 서치창 -->
    <div class="search-box">
      <form role="search" class="search-txt" action="{% url 'articles:search' %}">
        <input type="search" class="search-txt search-size" name="search" placeholder="닉네임, 제목, 내용을 검색해보세요.">
        <button class="search-btn" type="submit"><i class="bi bi-search"></i></button>
      </form>
    </div>

    <!-- 글쓰기 버튼 -->
    <div class="cb-div">
      <button type="button" class="create-button" onclick="location.href='{% url 'articles:create' %}'">글쓰기</button>
    </div>
  </div> <!-- search-create -->

  <div class="article-list">
    <hr class="contents-start">
    {% for article in question_list %}
    {% if  article.unname %}
    <a href="{% url 'articles:detail' article.pk%}">
      
      <!-- 글 제목 -->
      <p class="article-title">[{{article.category}}] {{ article.title }}</p>
      
      <!-- 기타 정보 -->
      <p class="user-comments">익명{{ article.user.pk }} ㅣ {{ article.create_at|date:'Y.m.d H:i'}} ㅣ 조회수 {{ article.hits }} ㅣ 좋아요
        {{ article.like_users.count }} ㅣ 댓글 수 {{article.comment_user.count}}</p>
      </a>
      <hr>
      {% else %}
      
      <a href="{% url 'articles:detail' article.pk%}">

        <!-- 글 제목 -->
        <p class="article-title">[{{article.category}}] {{ article.title }}</p>
  
        <!-- 기타 정보 -->
        <p class="user-comments">{{ article.user.nickname }} ㅣ {{ article.create_at|date:'Y.m.d H:i'}} ㅣ 조회수 {{ article.hits }} ㅣ 좋아요
          {{ article.like_users.count }} ㅣ 댓글 수 {{article.comment_user.count}}</p>
      </a>
      <hr>
      {% endif %}
    {% endfor %}
  </div> <!-- article-list -->

  <ul class="pagination justify-content-center">
    <!-- 이전페이지 -->
    {% if question_list.has_previous %}
      <li class="page-item">
        <a class="page-link " href="?page={{ question_list.previous_page_number }}">〈</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">〈</a>
      </li>
    {% endif %}
    <!-- 페이지리스트 -->
    {% for page_number in question_list.paginator.page_range %}
      {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
        {% if page_number == question_list.number %}
          <li class="page-item active" aria-current="page">
            <a class="page-link " href="?page={{ page_number }}">{{ page_number }}</a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link " href="?page={{ page_number }}">{{ page_number }}</a>
          </li>
        {% endif %}
      {% endif %}
    {% endfor %}
    <!-- 다음페이지 -->
    {% if question_list.has_next %}
      <li class="page-item">
        <a class="page-link " href="?page={{ question_list.next_page_number }}">〉</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">〉</a>
      </li>
    {% endif %}
  </ul>
  <!-- pagination -->
</div>
<!-- index-container -->
{% endblock %}

articles/templates/articles/search.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'articles/css/search.css' %}">
{% endblock css %}

{% block content %}
<div class="search-container">
  <!-- 질문 게시판 -->
  <p class="title">
    <a href="{% url 'articles:index' %}">QUESTION BOARD</a>
  </p>

  {% if question_list %}
  <!-- 검색 결과 안내 -->
  <p class="search-result">'<span class="search-for">{{ search }}</span>' 에 대한 검색결과 입니다.</p>

  <!-- 검색 결과 목록 -->
  <table class="search-table">
    <thead class="thead-text">
      <tr class="thead-tr">
        <th scope="col">NO.</th>
        <th scope="col">TITLE</th>
        <th scope="col">EDITER</th>
        <th scope="col">DATE</th>
        <th scope="col">VIEWS</th>
        <th scope="col">LIKE</th>
      </tr>
    </thead>

    <tbody>
      {% for article in question_list %}
      {% if not article.unname %}
      <tr class="tbody-tr">
        <!-- <th scope="row">{{forloop.revcounter}}</th> 이걸로하니까 다음페이지에서 1로 초기화된다-->
        <td scope="row">{{article.pk}}</td>
        <td class="title-td">
          <a href="{% url 'articles:detail' article.pk %}" class="search-title">
            {{article.title}}
            <span class="comments">[{{ article.comment_user.count }}]</span>
          </a>
        </td>
        <td class="nickname-td">{{ article.user.nickname }}</td>
        <td>{{ article.create_at|date:'Y.m.d. H:i' }}</td>
        <td>{{ article.hits }}</td>
        <td>{{ article.like_users.count }}</td>
      </tr>
      {% endif %}
      {% endfor %}
    </tbody>
  </table>


  <ul class="pagination justify-content-center">
    <!-- 이전페이지 -->
    {% if question_list.has_previous %}
    <li class="page-item">
      <a class="page-link " href="?page={{ question_list.previous_page_number }}">〈</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" tabindex="-1" aria-disabled="true" href="#">〈</a>
    </li>
    {% endif %}
    <!-- 페이지리스트 -->
    {% for page_number in question_list.paginator.page_range %}
    <!--% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5  %}-->
    {% if page_number == question_list.number %}
    <li class="page-item active" aria-current="page">
      <a class="page-link " href="?page={{ page_number }}">{{ page_number }}</a>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link " href="?page={{ page_number }}">{{ page_number }}</a>
    </li>
    {% endif %}
    <!--{% endif %-->
    {% endfor %}
    <!-- 다음페이지 -->
    {% if question_list.has_next %}
    <li class="page-item">
      <a class="page-link " href="?page={{ question_list.next_page_number }}">〉</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" tabindex="-1" aria-disabled="true" href="#">〉</a>
    </li>
    {% endif %}
  </ul> <!-- pagination -->
  {% else %}
  <p class="no-result">'<span class="search-for">{{ search }}</span>"에 대한 검색결과가 없습니다.</p>
  <p class="empty-text">다른 검색어를 입력하시거나 철자와 띄어쓰기를 확인해보세요.</p>
  <button type="button" onclick="location.href='{% url 'free:index' %}'">돌아가기</button>

</div>
{% endif %}
</div>

{% endblock%}

articles/templates/articles/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'articles/css/update.css' %}">
{% endblock css %}

{% block content %}
<div class="update-container">
  <p class="title">
    <a href="{% url 'articles:index' %}">QUESTION BOARD</a><br><span class="state-change">UPDATE</span>
  </p>
  <form action='' method='POST' enctype='multipart/form-data'>
    {% csrf_token %}
    {{ form.media }}
    {{ form.title }}
    {{ form.category }}
    {{ form.content }}
    <div class="id_unname">
      <span>익명선택 </span>
        &nbsp;{{form.unname}}
      </div>
    <div class="buttons">
      <input type="submit" value="수정" class="edit-button">
      <a href="{% url 'articles:detail' article.pk %}" class="back-button">취소</a>
    </div>
  </form>
</div> <!-- update-container -->
{% endblock %}