SS/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", views.main, name="main"),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("articles/", include("articles.urls")),
    path("gathering/", include("gathering.urls")),
    path("free/", include("free.urls")),
    path("notices/", include("notices.urls")),
    path("search/", views.search, name="search"),
    path("calendars/", include("calendars.urls")),
    path("mdeditor/", include("mdeditor.urls")),
    path("notes/", include("notes.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("<int:pk>/detail/", views.detail, name="detail"),
    path("<int:pk>/edit_profile/", views.edit_profile, name="edit_profile"),
    path("<int:pk>/password/", views.change_password, name="change_password"),
    path("<int:pk>/follow/", views.follow, name="follow"),
    path("<int:pk>/message/", views.message, name="message"),
    path("login/github", views.social_signup_request, name="social"),
    path("login/github/callback", views.social_signup_callback),
    path("<int:pk>/send/", views.send, name="send"),
    path("<int:pk>/message_delete/", views.message_delete, name="message_delete"),
]

articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    # 질문게시글
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:articles_pk>/", views.detail, name="detail"),
    path("<int:articles_pk>/update/", views.update, name="update"),
    path("<int:articles_pk>/delete/", views.delete, name="delete"),
    path("fail/", views.fail, name="fail"),
    # 댓글
    path("<int:articles_pk>/comment_create/", views.comment_create, name="comment_create"),
    path("<int:articles_pk>/comment_delete/<int:comment_pk>/delete/",views.comment_delete,name="comment_delete",),
    path("<int:articles_pk>/comment_update/<int:comment_pk>/update/",views.comment_update,name="comment_update",),
    path("<int:articles_pk>/recomment_create/<int:comment_pk>/", views.recomment_create, name='recomment_create'),
    path("<int:articles_pk>/recomment_delete/<int:comment_pk>/delete/<int:recomment_pk>/", views.recomment_delete, name="recomment_delete"),
    path("<int:articles_pk>/like/", views.like, name="like"),
    path("search/", views.search, name="search"),
]

free/urls.py
from django.urls import path
from . import views

app_name = "free"

urlpatterns = [
    # 자유게시글
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:free_pk>/", views.detail, name="detail"),
    path("<int:free_pk>/update/", views.update, name="update"),
    path("<int:free_pk>/delete/", views.delete, name="delete"),
    path("fail/", views.fail, name="fail"),
    # 댓글
    path("<int:free_pk>/comments_create/", views.comment_create, name="comment_create"),
    path("<int:free_pk>/comment_delete/<int:comment_pk>/delete/",views.comment_delete,name="comment_delete"),
    path("<int:free_pk>/comment_update/<int:comment_pk>/update/",views.comment_update,name="comment_update"),
    path("<int:free_pk>/recomment_create/<int:comment_pk>/", views.recomment_create, name='recomment_create'),
    path("<int:free_pk>/recomment_delete/<int:comment_pk>/delete/<int:recomment_pk>/", views.recomment_delete, name="recomment_delete"),
    path("<int:free_pk>/like/", views.like, name="like"),
    path("search/", views.search, name="search"),
]

notices/urls.py
from django.urls import path
from . import views

app_name = "notices"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:notices_pk>/", views.detail, name="detail"),
    path("<int:notices_pk>/update/", views.update, name="update"),
    path("<int:notices_pk>/delete/", views.delete, name="delete"),
]

templates/base.html
{% load django_bootstrap5 %}
{% load static %}

<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Siseon</title>
  <!--css-->
  {% bootstrap_css %}
  {% block css %}{% endblock css %}
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
  <style>
    @charset "UTF-8";
    /* 지원하는(안 깨지는) font-weight: 300, 400, 700 */
    @import url('https://webfontworld.github.io/naver/NanumSquareRound.css');
    @import url('https://cdn.rawgit.com/moonspam/NanumSquare/master/nanumsquare.css');
    @import url('https://fonts.googleapis.com/css2?family=Calistoga&display=swap');
    /* font-family: 'Calistoga', 'NEXON Lv2 Gothic'; */

    @font-face {
      font-family: 'NEXON Lv2 Gothic';
      src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-04@2.1/NEXON Lv2 Gothic.woff') format('woff');
      font-weight: normal;
      font-style: normal;
    }

    /* 배경 화면 */
    body {
      background-color: #f6f3e7;
      color: #434343;
      font-family: 'NEXON Lv2 Gothic', sans-serif;
      
    }

    .body-container {
      padding-top: 5rem;
      min-height: 100vh;
    }
  </style>
</head>

<body>
  <!-- navbar -->
  {% include "navbar.html" %}

  <!-- body -->
  <div class="body-container">
    {% block content %}{% endblock content %}
  </div>

  <!--footer-->
  {% include "footer.html" %}

  <!--javascript-->
  {% comment %} {% bootstrap_javascript %}
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js%22%3E"></script> {% endcomment %}

  {% block js %}
  <script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI="
    crossorigin="anonymous"></script>
  {% endblock js %}
</body>

</html>

templates/footer.html
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/footer.css' %}">
{% endblock css %}

<div class="footer">
    <div class="footer-container">
        <!-- 푸터에 들어갈 내용 -->
        <!-- 저작권 걸리는 게 존재하면 (C) 지워야 함 -->
        <p class="footer-text">Made by
            <span class="bold">
                <a href="https://github.com/HYUNSIK-JI">HYUNSIK</a>,
                <a href="https://github.com/kleenex1">GYUTAK</a>,
                <a href="https://github.com/baeseorim">SEORIM</a>,
                <a href="https://github.com/YoonDii">YOONJI</a>,
                <a href="https://github.com/hobin49">HOBIN</a></span><br>
            K-DIGITAL TRAINING 1기<br>
            (C) Siseon, 2022. All Right Reserved
        </p> <!-- footer-text -->
    </div> <!-- footer-container -->
</div> <!-- footer -->

templates/main.html
{% load static %}
{% load django_bootstrap5 %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/base.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">
<link rel="shortcut icon" type="image/x-icon" href="static/images/favicon1.png">
{% endblock css %}
{% block content %}
<!--title-->
<div class="container ">
  <div class="main-titles">
    <span class="first-letter mt-5">SISEON</span>
  </div>
  <!--login-->
  <!-- <div class="logins">
    <div class="login_control">
      <a href="{% url 'accounts:login' %}" class="login">로그인</a>
      <a href="{% url 'accounts:signup' %}" class="signup">회원가입</a>
    </div>
  </div> -->
  <!--card-->
  <section class="hero-section mt-4">
    <div class="card-grid">
      <a class="card cards" href="{% url 'articles:index' %}">
        <div class="card_background"></div>
        <div class="card_content">
          <h3 class="card_heading_big">질문게시판</h3>
          <div class="btn-control">
            <button type="button" class="btn btns" id="btn">입장하기</button>
          </div>
        </div>
      </a>
      <a class="card cards" href="{% url 'gathering:gathering-list' %}">
        <div class="card_background"></div>
        <div class="card_content">
          <h3 class="card_heading_small">모임</h3>
          <!-- <img class="active card_below_small" src="https://lh4.googleusercontent.com/i1RprwcvxhbN2TAMunNxS4RiNVT0DvlD9FNQCvPFuJ0=w140-h165-no"> -->
          <div>
            <button type="button" class="btn btn-light btns" id="btn">입장하기</button>
          </div> 
        </div>
      </a>
      <a class="card cards" href="{% url 'calendars:index' %}">
        <div class="card_background"></div>
        <div class="card_content">
          <h3 class="card_heading_small">달력</h3>
          <!-- <img class="active card_below_small" src="https://lh4.googleusercontent.com/i1RprwcvxhbN2TAMunNxS4RiNVT0DvlD9FNQCvPFuJ0=w140-h165-no"> -->
          <div class="btn-control">
            <button type="button" class="btn btn-light btns btns-small" id="btn_small">입장하기</button>
          </div> 
        </div>
      </a>
      <a class="card cards" href="{% url 'free:index' %}">
        <div class="card_background"></div>
        <div class="card_content">
          <h3 class="card_heading_big">자유게시판</h3>
          <!-- <img class="active card_below_big" src="https://lh4.googleusercontent.com/i1RprwcvxhbN2TAMunNxS4RiNVT0DvlD9FNQCvPFuJ0=w140-h165-no"> -->
          <div>
            <button type="button" class="btn btn-light btns" id="btn">입장하기</button>
          </div> 
        </div>
      </a>
    </div>
  </section>
</div>  

{% endblock content %}

templates/navbar.html
{% load static %}

{% block css %}
  <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
{% endblock css %}

<div class="navbar">
  <!-- 로고 -->
  <div class="logo">
    <a class="navbar-brand" href="{% url 'main' %}" style="color: #0b2f7d; font-weight: bold;">
      SISEON
    </a>
  </div>
  <!-- logo -->

  <!-- 카테고리 -->
  <div class="cate">
    <a class="a-cate nav-link" aria-current="page" href="{% url 'articles:index' %}">Question</a>
    <a class="a-cate nav-link" href="{% url 'gathering:gathering-list' %}">Gathering</a>
    <a class="a-cate nav-link" href="{% url 'calendars:index' %}">Calendar</a>
    <a class="a-cate nav-link" href="{% url 'free:index' %}">Community</a>
    <a class="a-cate nav-link" href="{% url 'notices:index' %}">Notice</a>
  </div>
  <!-- cate -->

  <!-- 서치창 -->
  <div class="nsearch-box">
    <form role="search" class="nsearch-txt" action="{% url 'search' %}">
      <input type="search" class="nsearch-txt" name="search" placeholder="닉네임, 제목, 내용을 검색해보세요.">
      <button class="nsearch-btn" type="submit">
        <i class="bi bi-search"></i>
      </button>
    </form>
  </div>

  <!-- 회원 정보 -->
  <div class="cate2">
    <div class="user-info">
      {% if request.user.is_authenticated %}
        <a class="user-cate nav-link" href="{% url 'accounts:detail' request.user.pk %}">
          Hi,
          {{ request.user.nickname }}</a>
        <a class="user-cate nav-link" href="{% url 'accounts:logout' %}">
          Logout</a>
      {% else %}
        <a class="user-cate nav-link" href="{% url 'accounts:login' %}">Login</a>
        <a class="user-cate nav-link" href="{% url 'accounts:signup' %}">Signup</a>
      {% endif %}
    </div>
    <!-- user-info -->

    <!-- 알람 -->
    <div class="alarm">
      <a class="alarm-cate nav-link" href="#" style="position:relative">
        Alarm
        {% if count > 0 %}
          <span class="position-absolute top-0 start-100 translate-middle p-1 bg-danger rounded-circle"></span>
        {% endif %}
        <!-- 실제 알람 내용-->
        <div class=" my-nav-window" id="nav-window">
          <div class=" messages">
            {% if count == 0 %}
              <p class="no-message">알림이 없습니다.</p>
            {% endif %}
            <div style="overflow: auto; height: 150px;">
              {% for n in request.user.notification_set.all %}
                {% if n.check == False %}
                  <div class="new-messages">
                    <a href="{% url 'accounts:message' n.pk %}">
                      {{n.message}}</a>
                    <hr>
                  </div>
                {% endif %}
                <!-- % if n.check == False % -->
              {% endfor %}
            </div>
            <!-- % for n in request.user.notification_set.all % -->

          </div>
          <!-- messages -->
        </div>
        <!-- my-nav-window -->
      </a>
      <!-- nav link -->
    </div>
    <!-- alarm -->
  </div>
  <!-- 공지 -->
  <!-- <div class="notice"> <a class="nav-link" href="{% url 'notices:index' %}">Notice</a> </div> -->
  <!-- notice -->
  <a href="#" class="ham">
    <svg class="ham" xmlns="http://www.w3.org/2000/svg" viewbox="0 0 448 512">
      <!--! Font Awesome Pro 6.2.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. -->
      <path d="M0 96C0 78.3 14.3 64 32 64H416c17.7 0 32 14.3 32 32s-14.3 32-32 32H32C14.3 128 0 113.7 0 96zM0 256c0-17.7 14.3-32 32-32H416c17.7 0 32 14.3 32 32s-14.3 32-32 32H32c-17.7 0-32-14.3-32-32zM448 416c0 17.7-14.3 32-32 32H32c-17.7 0-32-14.3-32-32s14.3-32 32-32H416c17.7 0 32 14.3 32 32z"/></svg>
  </a>
</div>
<!-- cate2 -->
</div>
<!-- navbar -->

{% block js %}
<script src="{% static 'js/navbar.js' %}"></script>
{% endblock js %}

templates/search.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/search.css' %}">
{% endblock css %}

{% block content %}

  <div class="search-container">
    <p class="title">TOTAL SEARCH</p>
  {% if question_list %}
  <!-- 검색 결과 안내 -->
  <p class="search-result">'<span class="search-for">{{ search }}</span>' 에 대한 검색결과 입니다.</p>

  <!-- 검색 결과 목록 -->
  <table class="search-table">
    <thead class="thead-text">
      <tr class="thead-tr">
        <th scope="col">CATEGORY</th>
        <th scope="col">TITLE</th>
        <th scope="col">EDITOR</th>
        <th scope="col">DATE</th>
        <th scope="col">VIEWS</th>
        <th scope="col">LIKE</th>
      </tr>
    </thead>
    <tbody>
      {% for all in question_list %}
      <tr class="tbody-tr">
        {% if all.q == "질문" %}
        {% if not all.unname %}
        <td class="fw-bold">{{all.q}}</td>
        <td class="title-td"><a href="{% url 'articles:detail' all.pk %}" class="search-title">{{all.title | truncatechars:10}}<span class="comments">[{{ all.comment_user.count }}]</span></a></td>
        <td class="nickname-td">{{all.user.nickname}}</td>
        <td>{{all.create_at|date:'Y.m.d'}}</td>
        
        <td>{{ all.hits }}</td>
        <td>{{ all.like_users.count }}</td>
        {% endif %}
      </tr>
      <tr>
      {% elif all.q == "자유" %}
        <td class="fw-bold">{{all.q}}</td>
        <td class="title-td"><a href="{% url 'free:detail' all.pk %}" class="search-title">{{all.title}}<span class="comments">[{{ all.free_user.count }}]</span></a></td>
        <td class="nickname-td">익명</td>
        <td>{{all.create_at|date:'Y.m.d'}}</td>
        
        <td>{{ all.hits }}</td>
        <td>{{ all.like_free.count }}</td>
      </tr>
      <tr>
      {% elif all.q == "모임" %}
        <td class="fw-bold">{{all.q}}</td>
        <td class="title-td"><a href="{% url 'gathering:gathering-detail' all.pk %}" class="search-title">{{all.title}}<span class="comments">[{{ all.gatheringcomments.count }}]</span></a></td>
        <td>{{all.user.nickname}}</td>
        <td>{{all.created_at|date:'Y.m.d'}}</td>
        
        <td>{{ all.hits }}</td>
        <td>{{ all.like_users.count }}</td>
        </tr>
      <tr>
      {% else %}
        <td class="fw-bold">공지</td>
        <td class="title-td"><a href="{% url 'notices:detail' all.pk %}" class="search-title">{{all.title}}</a></td>
        <td>@{{all.user.nickname|upper}}</td>
        <td>{{all.create_at|date:'Y.m.d'}}</td>
        <td>{{all.hits}}</td>
        <td>-</td>
        </tr>
        {% endif %}
        {% endfor %}
    </tbody>
  </table>
  <ul class="pagination justify-content-center">
    <!-- 이전페이지 -->
    {% if question_list.has_previous %}
    <li class="page-item">
      <a class="page-link " href="?search={{search}}&page={{ question_list.previous_page_number }}">〈</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" tabindex="-1" aria-disabled="true" href="#">〈</a>
    </li>
    {% endif %}
    <!-- 페이지리스트 -->
    {% for page_number in question_list.paginator.page_range %}
    {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5  %}
    {% if page_number == question_list.number %}
    <li class="page-item active" aria-current="page">
      <a class="page-link " href="?search={{search}}&page={{ page_number }}">{{ page_number }}</a>
    </li>
    {% else %} 
    <li class="page-item">
      <a class="page-link " href="?search={{search}}&page={{ page_number }}">{{ page_number }}</a>
    </li>
    {% endif %}
    {% endif %} 
    {% endfor %}
    <!-- 다음페이지 -->
    {% if question_list.has_next %}
    <li class="page-item">
      <a class="page-link " href="?search={{search}}&page={{ question_list.next_page_number }}">〉</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" tabindex="-1" aria-disabled="true" href="#">〉</a>
    </li>
    {% endif %}
  </ul> <!-- pagination -->
  {% else %}
    <h3 class="m-0">{{ search }} "검색결과가 없어요"</h3>
  {% endif %}
</div>
{% endblock content%}